customer_information:
  procedure: ITDS_Get_Cust_Info
  parameters:
    Login: string
  return_fields:
    - Credit Line
    - Buy limit
    - Bought Value
    - Sold Value
    - Net Value
    - Commission1 & VAT
    - Commission2 & VAT
    - Sell limit
    - Commission3 & VAT
    - Cash Amount
customer_position:
  procedure: ITDS_Get_Cust_Posi
  parameters:
    CustId: string
  return_fields:
    - Stock
    - No. Of Share
    - Cost
    - Bid
    - Offer
    - Sellable
    - Last Price
    - Average Price
    - Trust No
    - Type
    - Net Settlement Value
    - Grade
customer_position_realized:
  procedure: ITDS_Get_Cust_Posi_Realize
  parameters:
    CustId: string
  return_fields:
    - Stock
    - No. Of Share
    - Cost
    - Bid
    - Offer
    - Sellable
    - Last Price
    - Average Price
    - Trust No
    - Type
    - Current Value
    - Sold Vol
    - Sold Avg Price
    - Sold Total Amount
    - Cost Average
    - Cost Total Amount
    - Unrealize
    - Realize
    - Start of Day
    - B/H Today
    - Net Settlement Value
get_order_information:
  procedure: ITDS_Get_Ord_Info
  parameters:
    CustID: string
#    iOrdNo: string
    StOrdNo: numeric
    Max: numeric
    Date: string
    Orderby: numeric
    SetOrdId: string
  return_fields:
    - sStatus
    - iOrdNo
    - sOrdType
    - sQT
    - sSide
    - sSec
    - sCPrice
    - nmrVol
    - nmrMatVol
    - dtLastUpd
    - AvgPrice
    - sSendDate
    - Trust No
    - nmrLocalVolume
    - nmrForeignVolume
    - bitApproval
    - Special Order Type
    - Publish Volume
    - Condition
    - sSETOrdId
    - Validity
    - ValidityData
get_deal_information:
  procedure: ITDS_Get_Deal_Info
  parameters:
    CustId: string
    OrdNo: numeric
    SendDate: string
    DealId: string
    TradeId: string
    cCommissionFlag: string
  output_parameters:
    - TotalCommission
    - TotalTradingFee
    - TotalClearingFee
    - TotalSettlementFee
    - TotalVAT
    - TotalCommVAT
    - TotalWithholdingTax
  return_fields:
    - iCnfrmNo
    - iOrdNo
    - sSide
    - sSec
    - sFirmNo
    - sContraFirm
    - nmrPrice
    - nmrVol
    - sSendDate
    - sTime
    - sOrdType
    - sServiceType
    - sMktId
    - iTrustNo
    - nmrCommVAT
    - sDealID
    - sTradeID
get_deal_history:
  procedure: ITDS_Get_Deal_History
  parameters:
    CustId: string
    StartDate: string
    EndDate: string
    DealId: string
    TradeId: string
  output_parameters:
    - TotalCommission
    - TotalTradingFee
    - TotalClearingFee
    - TotalSettlementFee
    - TotalVAT
    - TotalCommVAT
    - TotalWithholdingTax
  return_fields:
    - iCnfrmNo
    - iOrdNo
    - sSide
    - sSec
    - sFirmNo
    - sContraFirm
    - nmrPrice
    - nmrVol
    - sSendDate
    - sTime
    - sOrdType
    - sServiceType
    - sMktId
    - iTrustNo
    - nmrCommVAT
    - sDealId
    - sTradeId
new_order:
  procedure: ITDS_Put_Order
  parameters:
    LogIn: string
    Sec: string
    Side: string
    Volume: numeric
    Price: numeric
    TimeLmt: string
    Cond: string
    SendDate: string
    TrustNo: numeric
    UserNo: string
    SpOrdType: string
    PubVolume: string
    TradingChannel: string
    Validity: string
    ValidityDate: string
    Remark1: string
    Remark2: string
    Remark3: string
new_order_PG:
  procedure: ITDS_Put_PG_Order
  parameters:
    LogIn: string
    Sec: string
    Side: string
    Volume: numeric
    Price: numeric
    TimeLmt: string
    Cond: string
    SendDate: string
    TrustNo: numeric
    UserNo: string
    SpOrdType: string
    PubVolume: string
    StrategyID: string
    Position: string
cancel_order:
  procedure: ITDS_Put_Cancel_Order
  parameters:
    LogIn: string
    OrdNo: numeric
    SendDate: string
    TradingChannel: string
    CxlUserNo: string
    Remark1: string
    Remark2: string
    Remark3: string
amend_order:
  procedure: ITDS_Put_Change_Order
  parameters:
    OrdNo: numeric
    EntryDate: string
    Volume: numeric
    Price: numeric
    LogIn: string
    IcebergVolume: numeric
    TrustNo: numeric
    UserNo: string
    TradingChannel: string
    Validity: string
    ValidityDate: string
    Remark1: string
    Remark2: string
    Remark3: string
get_order_expand:
  procedure: ITDS_Get_Order_Expand
  parameters:
    CustId: string
    OrdNo: numeric
    SendDate: string
    SetOrdId: string
  return_fields:
    - Status
    - Time
    - Trader
    - Volume
    - Price
    - Customer
    - Market ID
    - Contra
    - UserID
    - Old Volume
    - Old Price
    - Old Account
    - ExpandDate
    - SET Order ID
get_rejected:
  procedure: ITDS_Get_Reject
  parameters:
    OrdNo: numeric
    RejDate: string
  return_fields:
    - iRejCode
    - sDesc